-- Popup chao mung ngau nhien (GIF + loi chao) khi dang nhap/mo lai web - xem
-- frontend/src/components/GreetingPopup.tsx + backend/src/routes/settings.ts
-- (/settings/greeting-gif, /settings/greeting-message). Danh muc co the them/bat-tat qua Settings,
-- KHONG ghi settings_audit_log (don gian hoa co y - day la tinh nang trang tri, khong can audit
-- trail nhu cac danh muc nghiep vu khac).
CREATE TABLE settings_greeting_gif (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    gif_url     TEXT NOT NULL UNIQUE,
    bat_tat     INTEGER NOT NULL DEFAULT 1,
    created_at  TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE settings_greeting_message (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    noi_dung    TEXT NOT NULL UNIQUE,
    bat_tat     INTEGER NOT NULL DEFAULT 1,
    created_at  TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

INSERT INTO settings_greeting_gif (gif_url) VALUES
    ('https://media1.tenor.com/m/3bVEZcee8_oAAAAC/dancing-mushroom.gif'),
    ('https://media1.tenor.com/m/skrULsl5twcAAAAC/bubududukiwi-twitter.gif'),
    ('https://media1.tenor.com/m/_YoesJxE1tYAAAAC/panda-%C3%B6p%C3%BCc%C3%BCk.gif'),
    ('https://media1.tenor.com/m/TdZh-I0yqp4AAAAC/%E5%95%A6%E5%95%A6%E5%95%A6%E5%95%A6.gif'),
    ('https://media1.tenor.com/m/_xr0HcLB4fAAAAAC/sticker.gif'),
    ('https://media1.tenor.com/m/7R2swwUfWKQAAAAC/hasher-sticker.gif'),
    ('https://media1.tenor.com/m/eM_uj10kanIAAAAC/tkthao219-quby.gif'),
    ('https://media1.tenor.com/m/O-MpFR5WKXQAAAAC/tkthao219-quby-sticker.gif'),
    ('https://media1.tenor.com/m/Qj40AdvEqKsAAAAC/bubu-happy.gif'),
    ('https://media1.tenor.com/m/WtQmgkIdrncAAAAC/journey-dance.gif');

INSERT INTO settings_greeting_message (noi_dung) VALUES
    ('Bạn ơi! Tôi nhớ bạn quá!'),
    ('Chăm chỉ như bạn, hợp với tôi quá!'),
    ('Cám ơn đã ghé lại, bạn có nhớ tôi không?'),
    ('Hôm nay trông bạn xinh/đẹp trai thế! Có bạn vào là cả trang web sáng bừng lên luôn.'),
    ('Bạn mà không đăng nhập là tôi tưởng bạn "bỏ rơi" tôi luôn rồi đó!'),
    ('Màn hình của tôi đang buồn, gặp bạn cái bừng sáng liền nè!'),
    ('Ú ôm một cái nào! Cuối cùng "người gánh team" cũng đã trở lại.'),
    ('Ting ting! Bạn đã nạp 100% năng lượng chưa? Bắt đầu chiến thôi nào!'),
    ('Cà phê đã sẵn sàng chưa? Mình cùng "sấy khô" cái đống deadline hôm nay nhé!'),
    ('Hôm nay nhất định sẽ là một ngày làm việc siêu mượt mà!'),
    ('Sạc đầy pin chưa bạn ơi? Cùng làm vài cú đúp bàn thắng hôm nay nào!'),
    ('Chào sếp tổng của vũ trụ công việc! Hôm nay chúng ta làm gì tiếp theo đây?'),
    ('Chào mừng bạn trở lại! Nhớ giải lao giữa giờ và uống đủ nước nha!'),
    ('Hôm nay làm sương sương thôi, nghỉ ngơi nữa nha bạn hiền!'),
    ('Hệ thống đã phát hiện một nhân sự siêu cấp chăm chỉ vừa đăng nhập!'),
    ('Bíp bíp! Đã nhận diện khuôn mặt dễ thương nhất hôm nay.'),
    ('Dữ liệu báo về: Bạn vừa xuất hiện, tỉ lệ hoàn thành công việc vọt lên 200%!'),
    ('Tôi đã khởi động lại mọi tính năng chỉ để chờ cú click của bạn đó!'),
    ('Cảnh báo: Mức độ làm việc chăm chỉ sắp vượt quá giới hạn cho phép!'),
    ('Server đang rung rinh vì sự trở lại quyến rũ của bạn đây!'),
    ('Vũ trụ bảo hôm nay bạn làm gì cũng sẽ gặp may mắn đó!'),
    ('Lại là bạn à? Thôi xong, hôm nay công việc lại chạy vèo vèo rồi!'),
    ('Alo alo! Vui lòng cất sự đáng yêu vào trong và bắt đầu làm việc nào!'),
    ('Đừng làm việc quá sức nha, bạn mà ốm là tôi không có ai nói chuyện cùng đâu!'),
    ('Tin chuẩn 100%: Sự chăm chỉ của bạn đang làm các đồng nghiệp trầm trồ đấy.'),
    ('Bạn đã quay lại! Deadline nghe thấy tên bạn cũng phải tự động lùi bước.'),
    ('Ngày mới rực rỡ nhé, người bạn tuyệt vời!'),
    ('Hôm nay sẽ là một ngày siêu năng suất cho mà xem!'),
    ('Chào bạn! Rất vui vì lại được đồng hành cùng bạn hôm nay.'),
    ('Sẵn sàng chinh phục thế giới chưa? Bắt đầu thôi!'),
    ('Alo 1234, hero xuất hiện!'),
    ('Lại là bạn à? Yêu thế!'),
    ('Cú click triệu đô đây rồi!'),
    ('Chào "trùm" gánh team!'),
    ('Ủa, ai mà đáng yêu vậy ta?'),
    ('Bật chế độ siêu năng suất!'),
    ('Deadline ơi, chào đại ca đi!'),
    ('Chờ mãi mới thấy bạn vào!'),
    ('Tốc độ đăng nhập: 10/10!'),
    ('Ting ting! Năng lượng đã đầy!'),
    ('Hôm nay làm sương sương thôi nha!'),
    ('Cùng "quét sạch" công việc nào!'),
    ('Chào bạn hiền, chiến thôi!'),
    ('Uống ngụm nước rồi làm tiếp nha!'),
    ('Nay trông thần thái lắm đó!'),
    ('Nút bấm này chờ bạn lâu lắm rồi!'),
    ('Chào sao hạng A của hệ thống!'),
    ('Mở máy lên là thấy may mắn!'),
    ('Vũ trụ gửi lời chào bạn!'),
    ('Làm tí việc rồi đi chill thôi!'),
    ('Đã kết nối với bộ não siêu việt!'),
    ('Hệ thống thả tim cho bạn!'),
    ('Nhận diện: VIP vừa đăng nhập.'),
    ('Server vừa ấm lên 2 độ C!'),
    ('Data báo: Hôm nay bạn sẽ thắng lớn!'),
    ('Kích hoạt chế độ gánh team!'),
    ('Tải thành công sự dễ thương!'),
    ('Sẵn sàng nhận lệnh từ sếp!'),
    ('Chỉ số chăm chỉ: Vượt trần!'),
    ('Cảm ơn vì đã quay lại với tôi!');
