-- 2026-10-10: bang quy doi TINH CU (63, truoc sap nhap 1/7/2025) -> TINH MOI (34) - "Dia gioi cu / moi" dung chung
-- moi bao cao. Ten luu dang CHUAN co tien to ("Tinh ..."/"Thanh pho ...", vd "Thanh pho Ha Noi"); frontend chuan hoa
-- ten tho trong du lieu (bo tien to, "Hoa"/"Hoà", "Thua Thien Hue" -> "Hue"...) roi so khop voi bang nay
-- (frontend/src/lib/diaGioi.ts) - server KHONG chuan hoa. Ca chua co tinh_moi (moi ca QuickSight cu) -> lay tinh moi
-- qua bang nay. Admin/TBP DVBH sua/them dong (vd them ten bien the la "Ha Tay") o Cai dat -> "Quy doi tinh".
CREATE TABLE tinh_quy_doi (
    tinh_cu   TEXT PRIMARY KEY,
    tinh_moi  TEXT NOT NULL,
    nguoi_sua TEXT,
    ngay_sua  TEXT
);

INSERT INTO tinh_quy_doi (tinh_cu, tinh_moi) VALUES
    ('Thành phố Hà Nội', 'Thành phố Hà Nội'),
    ('Thành phố Huế', 'Thành phố Huế'),
    ('Tỉnh Lai Châu', 'Tỉnh Lai Châu'),
    ('Tỉnh Điện Biên', 'Tỉnh Điện Biên'),
    ('Tỉnh Sơn La', 'Tỉnh Sơn La'),
    ('Tỉnh Lạng Sơn', 'Tỉnh Lạng Sơn'),
    ('Tỉnh Quảng Ninh', 'Tỉnh Quảng Ninh'),
    ('Tỉnh Thanh Hóa', 'Tỉnh Thanh Hóa'),
    ('Tỉnh Nghệ An', 'Tỉnh Nghệ An'),
    ('Tỉnh Hà Tĩnh', 'Tỉnh Hà Tĩnh'),
    ('Tỉnh Cao Bằng', 'Tỉnh Cao Bằng'),
    ('Tỉnh Tuyên Quang', 'Tỉnh Tuyên Quang'),
    ('Tỉnh Hà Giang', 'Tỉnh Tuyên Quang'),
    ('Tỉnh Lào Cai', 'Tỉnh Lào Cai'),
    ('Tỉnh Yên Bái', 'Tỉnh Lào Cai'),
    ('Tỉnh Thái Nguyên', 'Tỉnh Thái Nguyên'),
    ('Tỉnh Bắc Kạn', 'Tỉnh Thái Nguyên'),
    ('Tỉnh Phú Thọ', 'Tỉnh Phú Thọ'),
    ('Tỉnh Vĩnh Phúc', 'Tỉnh Phú Thọ'),
    ('Tỉnh Hòa Bình', 'Tỉnh Phú Thọ'),
    ('Tỉnh Bắc Ninh', 'Tỉnh Bắc Ninh'),
    ('Tỉnh Bắc Giang', 'Tỉnh Bắc Ninh'),
    ('Tỉnh Hưng Yên', 'Tỉnh Hưng Yên'),
    ('Tỉnh Thái Bình', 'Tỉnh Hưng Yên'),
    ('Thành phố Hải Phòng', 'Thành phố Hải Phòng'),
    ('Tỉnh Hải Dương', 'Thành phố Hải Phòng'),
    ('Tỉnh Ninh Bình', 'Tỉnh Ninh Bình'),
    ('Tỉnh Hà Nam', 'Tỉnh Ninh Bình'),
    ('Tỉnh Nam Định', 'Tỉnh Ninh Bình'),
    ('Tỉnh Quảng Trị', 'Tỉnh Quảng Trị'),
    ('Tỉnh Quảng Bình', 'Tỉnh Quảng Trị'),
    ('Thành phố Đà Nẵng', 'Thành phố Đà Nẵng'),
    ('Tỉnh Quảng Nam', 'Thành phố Đà Nẵng'),
    ('Tỉnh Quảng Ngãi', 'Tỉnh Quảng Ngãi'),
    ('Tỉnh Kon Tum', 'Tỉnh Quảng Ngãi'),
    ('Tỉnh Gia Lai', 'Tỉnh Gia Lai'),
    ('Tỉnh Bình Định', 'Tỉnh Gia Lai'),
    ('Tỉnh Khánh Hòa', 'Tỉnh Khánh Hòa'),
    ('Tỉnh Ninh Thuận', 'Tỉnh Khánh Hòa'),
    ('Tỉnh Lâm Đồng', 'Tỉnh Lâm Đồng'),
    ('Tỉnh Đắk Nông', 'Tỉnh Lâm Đồng'),
    ('Tỉnh Bình Thuận', 'Tỉnh Lâm Đồng'),
    ('Tỉnh Đắk Lắk', 'Tỉnh Đắk Lắk'),
    ('Tỉnh Phú Yên', 'Tỉnh Đắk Lắk'),
    ('Thành phố Hồ Chí Minh', 'Thành phố Hồ Chí Minh'),
    ('Tỉnh Bình Dương', 'Thành phố Hồ Chí Minh'),
    ('Tỉnh Bà Rịa - Vũng Tàu', 'Thành phố Hồ Chí Minh'),
    ('Tỉnh Đồng Nai', 'Tỉnh Đồng Nai'),
    ('Tỉnh Bình Phước', 'Tỉnh Đồng Nai'),
    ('Tỉnh Tây Ninh', 'Tỉnh Tây Ninh'),
    ('Tỉnh Long An', 'Tỉnh Tây Ninh'),
    ('Thành phố Cần Thơ', 'Thành phố Cần Thơ'),
    ('Tỉnh Sóc Trăng', 'Thành phố Cần Thơ'),
    ('Tỉnh Hậu Giang', 'Thành phố Cần Thơ'),
    ('Tỉnh Vĩnh Long', 'Tỉnh Vĩnh Long'),
    ('Tỉnh Bến Tre', 'Tỉnh Vĩnh Long'),
    ('Tỉnh Trà Vinh', 'Tỉnh Vĩnh Long'),
    ('Tỉnh Đồng Tháp', 'Tỉnh Đồng Tháp'),
    ('Tỉnh Tiền Giang', 'Tỉnh Đồng Tháp'),
    ('Tỉnh Cà Mau', 'Tỉnh Cà Mau'),
    ('Tỉnh Bạc Liêu', 'Tỉnh Cà Mau'),
    ('Tỉnh An Giang', 'Tỉnh An Giang'),
    ('Tỉnh Kiên Giang', 'Tỉnh An Giang');
