/**
 * Nhan tieng Viet dung chung cho cac cot cua case_dvbh (CaseRow) khi xuat Excel (xem exportExcel.ts).
 * Cac module xuat nguyen dong CaseRow (nhieu hon so cot hien tren man hinh) - dung dict nay lam nen,
 * roi ghi de vai key bang dung chu tren man hinh cua chinh module do neu can (vi du Backlog dung
 * "Tiếp nhận" ngan gon thay vi "Thời gian tiếp nhận").
 */
export const CASE_FIELD_LABELS: Record<string, string> = {
  id: "ID",
  khach_hang: "Khách hàng",
  link_crm: "Link CRM",
  seri_san_pham: "Serial",
  cach_thuc_xu_ly: "Cách thức xử lý",
  tinh: "Tỉnh",
  quan_huyen: "Quận/Huyện",
  khu_vuc: "Khu vực",
  hang: "Hãng",
  nhom_san_pham: "Model",
  nganh: "Ngành",
  loai_nganh: "Loại ngành",
  doi_tac: "Đối tác",
  ky_thuat_vien: "KTV",
  thoi_gian_cskh_tiep_nhan: "Thời gian tiếp nhận",
  mo_ta_loi: "Mô tả lỗi",
  thoi_gian_hen_xu_ly: "Thời gian hẹn xử lý",
  nhom_yeu_cau: "Nhóm yêu cầu",
  loai_yeu_cau: "Loại yêu cầu",
  san_pham_bao_hanh: "Sản phẩm bảo hành",
  hinh_thuc_bao_hanh: "Hình thức bảo hành",
  tien_do_hoan_thanh: "Tiến độ hoàn thành",
  thoi_gian_hoan_thanh: "Thời gian hoàn thành",
  luu_y_loi_linh_kien: "Lưu ý lỗi linh kiện",
  ly_do_huy: "Lý do huỷ",
  noi_dung_xu_ly: "Nội dung xử lý",
  ly_do_qua_han: "Lý do quá hạn",
  dt_san_pham: "DT sản phẩm",
  dt_linh_kien: "DT linh kiện",
  dt_dich_vu: "DT dịch vụ",
  dung_han: "Đúng hạn",
  xu_ly_24h_bucket: "Nhóm xử lý 24h",
  ngay_mua: "Ngày mua",
  nhom_kh: "Nhóm KH",
  link_hinh_anh: "Link hình ảnh",
  ngay_import: "Ngày import",
  ngay_cap_nhat_gan_nhat: "Ngày cập nhật gần nhất",
  assigned_to: "Phân công",
  archived_at: "Đã lưu trữ",
  huy_bo_at: "Thời gian huỷ",
  huy_bo_by: "Người huỷ",
  huy_bo_ly_do: "Lý do huỷ ca",
  loi_120p: "Lỗi 120 phút",
  loi_qua_han_24h: "Lỗi quá hạn 24h",
  loi_lo_ke_hoach: "Lỗi lỡ kế hoạch",
  loi_kh_hen_lai: "KH hẹn lại",
  nghi_ngo_nap_gas: "Nghi ngờ nạp gas",
  nghi_ngo_tranh_chap: "Nghi ngờ tranh chấp",
  // Cac cot nay co tren case_dvbh (SELECT c.* tra ve day du) nhung KHONG khai bao tren type CaseRow
  // (frontend/src/types.ts) - van phai co nhan o day de khong lo ra ten cot tho khi xuat Excel du
  // form nao trong app cung dang xuat NGUYEN dong tra ve tu API (nhieu hon field CaseRow khai bao).
  thoi_gian_goc_dong_ca: "Thời gian gốc đóng ca",
  so_phut_xu_ly: "Số phút xử lý",
  thoi_gian_tai_du_lieu_crm: "Thời gian tải dữ liệu CRM",
  created_at: "Ngày tạo (hệ thống)",
  updated_at: "Ngày cập nhật (hệ thống)",
  tinh_vao_kpi: "Tính vào KPI",
  ca_lap_prior_id: "ID ca lặp trước",
  ca_lap_prior_ht: "Hoàn thành ca lặp trước",
  ca_lap_computed_at: "Thời gian tính ca lặp",
  crm_hash: "Hash CRM (nội bộ)",
  nghi_ngo_tranh_chap_xac_nhan_boi: "Người xác nhận nghi ngờ tranh chấp",
  nghi_ngo_tranh_chap_xac_nhan_luc: "Thời gian xác nhận nghi ngờ tranh chấp",
  can_khao_sat: "Cần khảo sát",
  last_ly_do_cham: "Lý do tồn gần nhất",
  last_ngay_giai_trinh: "Ngày giải trình gần nhất",
  last_ngay_du_kien_hoan_thanh: "Ngày dự kiến hoàn thành gần nhất",
  last_ma_linh_kien_thieu: "Mã linh kiện thiếu gần nhất",
  last_ma_xuat_hang_lien_quan: "Mã xuất hàng liên quan gần nhất",
  last_noi_dung_giai_trinh: "Nội dung giải trình gần nhất",
  last_tranh_chap_trang_thai: "Trạng thái tranh chấp gần nhất",
  last_phan_loai_tranh_chap: "Phân loại tranh chấp gần nhất",
  tranh_chap_so_ngay_ton: "Số ngày tồn tranh chấp",
};
